### ISSUE TITLE
Sometimes it flashes twice when I open the DeaDBeeF player.

### ISSUE THREAD

**Issue by laichiaheng** [saivert/ddb_misc_headerbar_GTK3#6]
I can't record it by recording applications, so I record it by my phone.
https://youtu.be/Gfw6hXNYKOs
It happens at the first time of the video.

**Comment by saivert** [comment]
This is a known bug and will not likely be fixed. I have a solution but it would require changes to the deadbeef core.

Technical explanation:
This plugin calls gtk_window_set_titlebar() which repositions the window due to a GTK or Window manager bug. The plugin will then restore the position from the deadbeef configuration. In order to avoid seeing the window at one position and then see it move to the correct position I hide the window temporarily. This causes the flashing you see when deadbeef starts up.

**Comment by Oleksiy-Yakovenko** [comment]
@saivert if the changes in deadbeef core are not destructive - I will accept or make the fix which you need. What do you have in mind?

**Comment by saivert** [comment]
My plugin needs to be able to call gtk_window_set_titlebar() before mainwin is realized.
That is before gtkui plugin calls gtk_widget_show(mainwin). So there would have to be some kind or window of opportunity for other plugins to do stuff before that happens. How you implement this is up to you @Alexey-Yakovenko
